
import { NgModule } from '@angular/core';


import {MatSidenavModule,
        MatMenuModule,
        MatInputModule,
        MatButtonModule,
        MatCardModule,
        MatTooltipModule,
        MatSelectModule,
        MatCheckboxModule,
        MatIconModule,
        MatPaginatorModule,
        MatDialogModule,
        MatListModule,
        MatSortModule,
        MatTableModule,
        MatChipsModule,
        MatAutocompleteModule,
        MatProgressSpinnerModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatSnackBarModule,
        MatTabsModule,
        MatExpansionModule,
        MatRadioModule,
        MatTreeModule,
        MatToolbarModule,
        MatBadgeModule,
        MatBottomSheetModule
        
      } from '@angular/material';

@NgModule({
  imports: [MatSidenavModule,
            MatMenuModule,
            MatInputModule,
            MatButtonModule,
            MatCardModule,
            MatTooltipModule,
            MatSelectModule,
            MatCheckboxModule,
            MatIconModule,
            MatPaginatorModule,
            MatDialogModule,
            MatListModule,
            MatSortModule,
            MatTableModule,
            MatChipsModule,
            MatProgressSpinnerModule,
            MatAutocompleteModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatSnackBarModule,
            MatTabsModule,
            MatExpansionModule,
            MatRadioModule,
            MatTreeModule,
            MatToolbarModule,
            MatBadgeModule,
            MatBottomSheetModule
          ],
  exports: [MatSidenavModule,
            MatMenuModule,
            MatInputModule,
            MatButtonModule,
            MatCardModule,
            MatTooltipModule,
            MatSelectModule,
            MatCheckboxModule,
            MatIconModule,
            MatPaginatorModule,
            MatDialogModule,
            MatListModule,
            MatSortModule,
            MatTableModule,
            MatChipsModule,
            MatAutocompleteModule,
            MatProgressSpinnerModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatSnackBarModule,
            MatTabsModule,
            MatExpansionModule,
            MatRadioModule,
            MatTreeModule,
            MatToolbarModule,
            MatBadgeModule,
            MatBottomSheetModule
          ]
})
export class MaterialModule { }
